Update cleanprefix

diff --git a/cleanprefix b/cleanprefix
--- a/cleanprefix
+++ b/cleanprefix
@@ -4,13 +4,20 @@
 # It works in bash, the low quality of this file demonstrates my unskilled
 # talent in shell scripts.
 #
-# -- Bruno Jesus 2013 - Unlicense
+# /!\ To destroy the prefix you can issue the command "__suicideprefix-yes".
+#
+# -- Bruno Jesus 2013 - Unlicense - Use at your own risk
 
 TEMPBASE=/media/ramdisk
 
 if [ "x$1" != "xwine32" -a "x$1" != "xwine64" ]; then
   echo "Incorrect first parameter, must be wine32 or wine64"
   exit 1;
+fi
+
+if ! type $1 2> /dev/null; then
+  echo "The command $1 was not found!"
+  exit 2
 fi
 
 TEMPFILE=`tempfile`
@@ -20,9 +27,9 @@ mkdir -p "$WINEPREFIX"
 WINEPREFIX=$WINEPREFIX $1 winecfg &
 WINEVER=`$1 --version`
 sleep 2
-echo "printf \"==================================================\n   ARCH      $1\n   VERSION   $WINEVER\n   PREFIX    $WINEPREFIX\n==================================================\n\"; export WINEPREFIX=$WINEPREFIX;alias wine=$1" > $TEMPFILE
+echo "printf \"==================================================\n   ARCH      $1\n   VERSION   $WINEVER\n   PREFIX    $WINEPREFIX\n==================================================\n\"; export WINEPREFIX=$WINEPREFIX;alias wine=$1;alias __suicideprefix-yes=\"rm -rf '$WINEPREFIX';kill -9 \$\$\"" > $TEMPFILE
 chmod +x $TEMPFILE
-uxterm -e "cd $WINEPREFIX/drive_c && source $TEMPFILE && /bin/bash" &
+uxterm -T "$1 - $WINEPREFIX" -e "cd $WINEPREFIX/drive_c && /bin/bash --init-file $TEMPFILE" &
 sleep 2
-rm $TEMPFILE
+#rm $TEMPFILE
 exit 0
